name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Generate .env
      run: |
        echo "VITE_KAKAO_APP_KEY=${{ secrets.KAKAO_APP_KEY }}" >> .env
        echo "VITE_KAKAO_JAVASCRIPT_KEY=${{ secrets.KAKAO_JAVASCRIPT_KEY }}" >> .env
        echo "VITE_GROOM_NAME=${{ secrets.GROOM_NAME }}" >> .env
        echo "VITE_BRIDE_NAME=${{ secrets.BRIDE_NAME }}" >> .env
        echo "VITE_GROOM_FATHER_NAME=${{ secrets.GROOM_FATHER_NAME }}" >> .env
        echo "VITE_GROOM_MOTHER_NAME=${{ secrets.GROOM_MOTHER_NAME }}" >> .env
        echo "VITE_BRIDE_FATHER_NAME=${{ secrets.BRIDE_FATHER_NAME }}" >> .env
        echo "VITE_BRIDE_MOTHER_NAME=${{ secrets.BRIDE_MOTHER_NAME }}" >> .env
        echo "VITE_GROOM_ACCOUNT=${{ secrets.GROOM_ACCOUNT }}" >> .env
        echo "VITE_BRIDE_ACCOUNT=${{ secrets.BRIDE_ACCOUNT }}" >> .env
        echo "VITE_GROOM_FATHER_ACCOUNT=${{ secrets.GROOM_FATHER_ACCOUNT }}" >> .env
        echo "VITE_GROOM_MOTHER_ACCOUNT=${{ secrets.GROOM_MOTHER_ACCOUNT }}" >> .env
        echo "VITE_BRIDE_FATHER_ACCOUNT=${{ secrets.BRIDE_FATHER_ACCOUNT }}" >> .env
        echo "VITE_BRIDE_MOTHER_ACCOUNT=${{ secrets.BRIDE_MOTHER_ACCOUNT }}" >> .env

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist